modeltranslation/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

# ModelTranslationURLs
from modeltranslation.admin import views


class ModelTranslationUrls(object):
	def __init__(self, name='modeltranslation', app_name='modeltranslation'):
		self.app_name = app_name # App Namespace
		self.name = name # Instance Namespace

	urlpatterns = [
		url(r'^$', views.admin, name="admin_url"),
		url(r'^(?P<language>[-\w]+)/(?P<filter>(all|completed|fuzzy)*)$', views.view_all, name="view_all_url"), # Translation management
		url(r'^edit_translation/(?P<translation>.*)$', views.edit, name="edit_url"), # Edition
		url(r'^import/(?P<language>[-\w]+)$', views.import_translations, name="import_translations_url"), # Translation import
		url(r'^export/(?P<language>[-\w]+)$', views.export_translations, name="export_translations_url"), # Translation export
		url(r'^update_translations$', views.update_translations, name="update_translations_url"), # Update translations
	]

	@property
	def urls(self):
		return (self.urlpatterns, self.app_name, self.name)

modeltranslation/templates/modeltranslation/admin/admin.html
{# {% extends "base_admin.html" %} #}

{% extends "admin/index.html" %}
{% load i18n %}
{% load static from staticfiles %}


{% block js %}
	{{ block.super }}
	<script type="text/javascript" src="{% static 'js/lib/sugar-1.3.9-full.development.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/modeltranslation/import.js' %}"></script>
{% endblock js %}

{% block custom-css %}
	{{ block.super }}
	<link rel="stylesheet" href="{% static 'css/modeltranslation/import.css' %}" />
{% endblock %}

{% block head_title %}
	Administrar Traducciones
{% endblock %}

{% block breadcrumbs %}
	<div class="breadcrumbs">
		<a href="{% url 'admin:index' %}" class="first">{% trans "Home"%}</a>  &rsaquo;
		<a href="{% url 'admin:index' %}modeltranslation" class="first">Modeltranslations</a> &rsaquo;
		<a href="{% url 'modeltranslation:admin_url' %}" class="first">{% trans "Translations" %}</a>
		{% block breadcrumb_element %}
		{% endblock breadcrumb_element %}
	</div>
{% endblock breadcrumbs %}

{% block body %}
	<div id="body-content" class="span12">
		<div id="content-title" class="page-header">
			<h1>
				{%block title %}
					Administrar Traducciones
				{% endblock %}
			</h1>
		</div>

		<div id="content" class="">
			{% block content %}
				<div id="translation_admin_list">
					<h2>Lista de idiomas existentes:</h2>
					{% get_language_info_list for LANGUAGES as languages %}
					{% if languages|length > 0 %}
						<ul id="translation_list" class="unstyled">
						{% for lang in languages %}
							{% if LANGUAGE_CODE != lang.code %}
								{% cycle 'odd' 'even' as parity silent %}
								<li id="{{ lang.code }}" class="language {{ parity }}">
									<div class="container-li">
										<div class="btn-toolbar tpv_admin_links_list">
											<div class="btn-group">
												<a title="Ver traducción en {{lang.name_local|capfirst}}" href="{% url 'modeltranslation:view_all_url' lang.code 'all' %}" class="btn btn-mini"><span class="fa fa-eye"></span> {{lang.name_local|capfirst}}</a>
												
												<form class="import" method="post" action="{% url 'modeltranslation:import_translations_url' lang.code %}" enctype="multipart/form-data" >
													<fieldset id="import_{{lang.code}}" class="btn-group import">
														<input id="translation_file_{{lang.code}}" class="translation_file btn" type="file" name="file" />
														<input id="import_submit_{{lang.code}}" class="import_submit btn btn-mini" type="submit" name="" value="Enviar fichero" />
													</fieldset>
												</form>
												
												<a title="Importar traducción desde un fichero .po" href="javascript:void(0);" class="import-link btn btn-mini"><span class="fa fa-download"></span> Importar traducción</a>
												<a title="Exportar traducción a un fichero .po" href="{% url 'modeltranslation:export_translations_url' lang.code %}" class="export-link btn btn-mini"><span class="fa fa-upload"></span> Exportar traducción</a>
											</div>
										</div>
									</div>
								</li>
							{% endif %}
						{% endfor %}
						</ul>
					{% else %}
						<div class="alert alert-warning">No hay idiomas disponibles</div>
					{% endif %}
				</div>
				<h2>Acciones de administración</h2>
				<div class="translation_admin_actions">
					<a title="Actualizar traducciones" href="{% url 'modeltranslation:update_translations_url' %}" class="btn"><span class="fa fa-reload-alt"></span> Actualizar traducciones</a>
				</div>
			{% endblock content %}
		</div>
	</div>
{% endblock %}

modeltranslation/templates/modeltranslation/admin/edit_translation.html
{% extends "modeltranslation/admin/admin.html" %}
{% load thumbnail %}
{% load i18n %}

{% block head_title %}
	Traducir al {{language}} &quot;{{translation.source_text|truncatewords:10|striptags}}&quot;
{% endblock %}

{% block css %}
	{{ block.super }}
	{{ form.media.css }}
{% endblock css %}

{% block js %}
	{{ block.super }}
	{{ form.media.js }}
{% endblock js %}

{% block breadcrumb_element %}
	{{ block.super }}
	&rsaquo;
	<a href="{% url 'modeltranslation:view_all_url' translation.lang 'all' %}" class="first">Traducciones a {{language}}</a>
	&rsaquo;
	<a href="{% url 'modeltranslation:edit_url' translation.id %}" class="first">Traducir al {{language}} &quot;{{translation.source_text|truncatewords:10|striptags}}&quot;</a>
{% endblock breadcrumb_element %}

{% block body %}
	<div id="body-content" class="span12">
		<div id="content-title" class="page-header">
			<h1>
				{%block title %}
					Traducir al {{language}} &quot;{{translation.source_text|truncatechars:30|striptags}}&quot;
				{% endblock %}
			</h1>
		</div>

		<div id="content" class="">
			{% block content %}
				<div id="tpvs_admin_list">
					<form id="form_banner" class="form-horizontal" method="post">
						{% csrf_token %}
						<fieldset>
							<legend>Texto original</legend>
							<div id="source_text" class="source_text">
								{{translation.source_text|safe}}
							</div>
							<legend>Texto traducido</legend>
							{% include "modeltranslation/admin/form_fieldset_bootstrap_render.html" %}
						</fieldset>

						 <div class="form-actions">
							<button type="submit" class="btn" name="cancel" value="Cancelar">
								<span class="fa fa-times"></span> Cancelar
							</button>
							<button type="submit" class="btn btn-primary" name="save" value="Guardar">
								<span class="fa fa-floppy-o"></span> Guardar
							</button>
						</div>
					</form>
				</div>
			{% endblock content %}
		</div>
	</div>
{% endblock %}

modeltranslation/templates/modeltranslation/admin/form_fieldset_bootstrap_render.html
{% for field in form %}
	<div class="control-group {% if field.errors %}error{% endif %}">
		<label class="control-label" for="id_{{ field.html_name }}">{{ field.label }}</label>
		<div class="controls">
			{{ field }}
			<span class="help-block help_text">
				{{ field.help_text }}
			</span>
			<span class="help-block errors">
				{{ field.errors }}
			</span>
		</div>
	</div>
{% endfor %}	        

modeltranslation/templates/modeltranslation/admin/list.html
{% extends "modeltranslation/admin/admin.html" %}

{% load static from staticfiles %}
{% load thumbnail %}
{% load i18n %}

{% block custom-css %}
	{{ block.super }}
	<link rel="stylesheet" href="{% static 'css/modeltranslation/search.css' %}" />
{% endblock %}

{% block head_title %}
	Administrate translations
{% endblock %}

{% block breadcrumb_element %}
	{{ block.super }}
	&rsaquo;
	<a href="{% url 'modeltranslation:view_all_url' lang 'all' %}" class="first">Translations to {{language}}</a>
	{% if filter and filter != "all" %}
			&rsaquo;
			<a href="{% url 'modeltranslation:view_all_url' lang filter %}" class="first">
				{% if filter == "fuzzy" %}
					Incomplete
				{% elif filter == "completed" %}
					Complete
				{% endif %}
			</a>
	{% endif %}
	{% if search_query %}
		&rsaquo;
		<a href="{% url 'modeltranslation:view_all_url' lang filter %}?search={{search_query}}" class="first">Results</a>
	{% endif %}
{% endblock breadcrumb_element %}

{% block body %}

	<div id="body-content" class="span12">
		<div id="content-title" class="page-header">
			<h1>
				{%block title %}
					Administrate translations to {{language}}
				{% endblock %}
			</h1>
		</div>

		<div id="content" class="">
			{% block content %}
				{% include "modeltranslation/admin/search.html" %}
				<div id="tpvs_admin_list">
					<h2>List of existing texts:</h2>
					{% if translations|length > 0 %}
						<div id="translation_list" class="row-fluid">
							<table class="table table-hover table-striped">
								<tr>
									<th class="span2">Model</th>
									<th class="span3">Attribute</th>
									<th class="span5">Source text</th>
									<th class="span5">Translation</th>
									<th class="span1">Actions</th>
								</tr>
								{% for translation in translations %}
									{% cycle 'odd' 'even' as parity silent %}
									{% with verbose_field_name=translation.get_verbose_field_name source_text=translation.source_text translation_text=translation.translation %}
										<tr id="translation__{{translation.id}}" class="{{parity}} model-{{translation.model}}">
											<td class="span2">{{translation.source_model.meta__verbose_name.title}}</td>
											<td class="span3">{{verbose_field_name}}</td>
											<td class="span5">{{source_text|truncatewords:20}}</td>
											<td class="span5">{{translation_text|truncatewords:20}}</td>
											<td class="span1">
												<a title="Editar traducción" href="{% url 'modeltranslation:edit_url' translation.id %}"><span class="fa fa-flag icon"></span></a>
											</td>
										</tr>
									{% endwith %}
								{% endfor %}
							</table>
						</div>
					{% else %}
						<div class="alert alert-warning">There are no translations for this language</div>
					{% endif %}

				</div>
			{% endblock content %}
		</div>
	</div>
{% endblock %}

modeltranslation/templates/modeltranslation/admin/search.html
{% load i18n %}

{% block translation_search %}

<div id="search-form" class="search-form row-fluid">
	<form method="post" action="{% url 'modeltranslation:view_all_url' lang filter %}">
		{% csrf_token %}
		<fieldset id="search-form-fieldset">

			<div class="control-groups">
				<div class="control-group">
					<div id="search-input" class="controls">
						<input class="" id="id-search" type="text" name="search" maxlength="50" value="{{search_query}}" placeholder="Buscar cadena">
					</div>
				</div>
				
				<div id="filter-group" class="filter-group filters">
					<div class="control-group">
						<label for="filter">Filtro</label>
						<div id="filter-select" class="controls">
							<select class="" id="id-filter" name="filter">
									<option id='option-all' value='all' {% if filter == "all" %}selected=selected{% endif %}>All</option>
									<option id='option-fuzzy' value='fuzzy' {% if filter == "fuzzy" %}selected=selected{% endif %}>Incomplete</option>
									<option id='option-completed' value='completed' {% if filter == "completed" %}selected=selected{% endif %}>Complete</option>
							</select>
						</div>
					</div>
					
					<div class="control-group">
						<label for="filter">Language</label>
						<div id="language-select" class="controls">
							<select class="" id="id-language" name="language">
									{% get_language_info_list for LANGUAGES as languages %}
									{% for language in languages %}
										{% if language.code != LANGUAGE_CODE %}
											<option id="option-{{language.code}}" value='{{language.code}}' {% if language.code == lang %}selected=selected{% endif %}>{{language.name_local|capfirst}}</option>
										{% endif %}
									{% endfor %}
							</select>
						</div>
					</div>
				</div>
			</div>
			
			<button id="search-button" class="btn disable_on_click transition" type="submit" name="submit" value="Buscar">
				<span class="fa fa-search"></span>
				<span class="button-txt">Search</span>
			</button>
		</fieldset>
	</form>
</div>

{% endblock translation_search %}

modeltranslation/templates/modeltranslation/admin/update_translations_ok.html
{% extends "modeltranslation/admin/admin.html" %}

{% load static from staticfiles %}
{% load thumbnail %}
{% load i18n %}

{% block custom-css %}
	{{ block.super }}
	<link rel="stylesheet" href="{% static 'css/modeltranslation/search.css' %}" />
{% endblock %}

{% block head_title %}
	Admin translations
{% endblock %}

{% block breadcrumb_element %}
	{{ block.super }}
	<li class="">
		<span class="divider">/</span>
		<a href="{% url 'modeltranslation:update_translations_url' %}" class="first">Translations update</a>
	</li>
{% endblock breadcrumb_element %}

{% block body %}
	<div id="body-content" class="span12">
		<div id="content-title" class="page-header">
			<h1>
				{%block title %}
					Success
				{% endblock %}
			</h1>
		</div>

		<div id="content" class="">
			{% block content %}
				{{num_translations}} texts has been translated.
				<div class="translation_admin_actions">
					<a href="{% url 'modeltranslation:admin_url' %}" class="btn"><span class="fa fa-reload-alt"></span> Back</a>
				</div>
			{% endblock content %}
		</div>
	</div>
{% endblock %}